### ISSUE TITLE
Report on filesize?

### ISSUE THREAD

**Issue by eeeps** [filamentgroup/imaging-heap#1]
Per Jason Grigsby’s idea of [“responsive image breakpoints”](https://cloudfour.com/thinks/responsive-images-101-part-9-image-breakpoints/), the *really* important thing to count, when it comes to upscaled/downscaled responsive resources, isn’t pixels – it’s bytes.

It's a bit of a tricky problem, but could the tool try to do what [Sizer Soze](https://www.sizersoze.org) used to, and report on how many bytes you would’ve saved if you’d served perfectly-sized resources?

**Comment by zachleat** [comment]
Yes! I like it! I wonder how much headless chrome exposes here. I don’t see anything on first glance at https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md

**Comment by zachleat** [comment]
Idea from https://twitter.com/eQRoeil/status/976563237826285569

```
performance.getEntriesByType("resource").filter(function(r){ return (r.initiatorType === 'img' && r.encodedBodySize > 100000)})
```
