### ISSUE TITLE
Add node version info

### ISSUE THREAD

**Issue by fatihhayri** [filamentgroup/imaging-heap#4]
The node 6 version was installed on my computer. imageheap did not work. Then I tried to install node v8.9.3.

**Comment by zachleat** [comment]
Hmm, node version support is declared in `package.json`: https://github.com/filamentgroup/imaging-heap/blob/master/package.json#L7

Can you be more specific about what you expect?

**Comment by fatihhayri** [comment]
You can add This information to README file.
